# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Flickr-Upload
version:      1.27
version_from: 
installdirs:  site
requires:
    Flickr::API:                   0.07
    Getopt::Long:                  1
    HTTP::Request::Common:         1
    LWP::UserAgent:                1
    Pod::Usage:                    1
    XML::Parser::Lite::Tree:       0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
