--- #YAML:1.0
name:               Flickr-Upload
version:            1.4
abstract:           Module for uploading images to flickr.com
author:
    - Christophe Beauregard <cpb@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Flickr::API:          0.07
    Getopt::Long:         1
    HTTP::Request::Common:  1
    LWP::UserAgent:       1
    Pod::Usage:           1
    XML::Parser::Lite::Tree:  0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
